### ISSUE TITLE
When I try to start the game in single mode  it shows this message ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by ccsalazarj89** [louis2889184/TetrisBattle#4]
pygame 2.0.1 (SDL 2.0.14, Python 3.7.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/csalazar/anaconda3/envs/tetris_battle/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/csalazar/anaconda3/envs/tetris_battle/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/csalazar/tetris-battle/TetrisBattle/game/tetris_game.py", line 7, in <module>
    from TetrisBattle.renderer import Renderer
  File "/home/csalazar/tetris-battle/TetrisBattle/TetrisBattle/renderer.py", line 2, in <module>
    from .tetris import collideDown, hardDrop
  File "/home/csalazar/tetris-battle/TetrisBattle/TetrisBattle/tetris.py", line 17, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by ccsalazarj89** [comment]
I fixed installing numPy with pip.
